"""Download the PID datasets of the *_icassp2027 configs into data/ (needed for Figs. 3 and 4).

Test-split evaluation datasets (tasks, reference, PID and Oracle solves) and
PID training caches, as generated by scripts/generate-pid-dataset.sh.

    python paper/download_data.py
"""

from huggingface_hub import snapshot_download

from paper.utils import DATASET_REPO, REPO_ROOT

if __name__ == "__main__":
    path = snapshot_download(
        DATASET_REPO, repo_type="dataset", local_dir=REPO_ROOT, allow_patterns=["data/*"]
    )
    print(f"[+] {DATASET_REPO} -> {path}/data")
