"""Shared helpers for the ICASSP 2027 figure scripts: paper models, datasets, DeepONet and solves.

JAX/steppo are imported inside the functions that need them, so the DeepONet
timing script can import the constants below in the PyTorch container.

Every figure script takes --mode:
  import   (default) StePPO models and DeepONets from Hugging Face.
  execute  models trained here: StePPO by paper/train.sh into
           outputs/paper/models/<system>/, DeepONet by
           train_deeponet_unified.py --profile retrain in the DeepONet container.
Both modes read the datasets in data/ (paper/download_data.py, or
generated by paper/train.sh).
"""

import collections
import csv
import glob
import os
import pickle
import zipfile

import numpy as np

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT_DIR = os.path.join(REPO_ROOT, "outputs", "paper")
DATASET_REPO = "MKoumans/steppo-icassp2027-data"
DEEPONET_REPO = "MKoumans/deeponet"

# Per system: training config and DeepONet revisions (StePPO models: steppo.cli.PAPER_MODELS).
SYSTEMS = {
    "scalar_decay": dict(
        config="configs/envs/ode/scalar_decay/scalar_decay_icassp2027.yaml",
        deeponet={"complete": "sd-complete"},
        label="λ",
    ),
    "van_der_pol": dict(
        config="configs/envs/ode/van_der_pol/van_der_pol_icassp2027.yaml",
        deeponet={"complete": "vdp-complete", "binned": "vdp-binned"},
        label="μ",
    ),
    "brusselator": dict(
        config="configs/envs/ode/brusselator/brusselator_icassp2027.yaml",
        deeponet={"complete": "bru-complete"},
        label="B",
    ),
}
COLORS = {
    "PID": "#4472C4",
    "StePPO": "#2CA02C",
    "Oracle": "#7F7F7F",
    "DeepONet": "#C00000",
    "DeepONet (binned)": "#FF7F0E",
    "Reference": "#000000",
}
DEEPONET_N_T = 200  # DeepONet training grid: DEEPONET_N_T points on [0, t_end]
MODES = ("import", "execute")
LOCAL_STEPPO_DIR = os.path.join(OUT_DIR, "models")  # execute mode: paper/train.sh output
LOCAL_DEEPONET_DIR = os.path.join(REPO_ROOT, "research", "baselines", "deeponet", "output-deeponet")
# Fig. 5 wall-clock sweep (Van der Pol, one sample per solve): task values, repeats per value, step budget.
WALLCLOCK_XI = np.geomspace(1.0, 50.0, 20)
WALLCLOCK_REPEATS = 10
WALLCLOCK_MAX_STEPS = 8192


def out_path(name: str) -> str:
    """Path under outputs/paper/, creating the directory."""
    os.makedirs(OUT_DIR, exist_ok=True)
    return os.path.join(OUT_DIR, name)


def save_csv(path: str, series: dict) -> None:
    """Write {method: {column: 1-D array}} as one long-format CSV with a leading `method` column."""
    columns = list(dict.fromkeys(c for cols in series.values() for c in cols))
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["method"] + columns)
        for method, cols in series.items():
            n = len(next(iter(cols.values())))
            for i in range(n):
                writer.writerow(
                    [method] + [f"{cols[c][i]:.8g}" if c in cols else "" for c in columns]
                )
    print(f"[+] {path}")


def add_mode_argument(parser) -> None:
    """Add --mode {import,execute} (see the module docstring)."""
    parser.add_argument(
        "--mode",
        choices=MODES,
        default="import",
        help="import: models from Hugging Face; execute: models trained locally",
    )


def load_config(system: str):
    """The system's *_icassp2027 TrainConfig, with its precision applied."""
    from steppo.configs.base_config import TrainConfig, apply_precision, load_config_from_yaml
    from steppo.envs.ode import ODEEnv  # noqa: F401 — import order avoids a circular import

    config = load_config_from_yaml(TrainConfig, os.path.join(REPO_ROOT, SYSTEMS[system]["config"]))
    apply_precision(config)
    return config


def load_steppo(system: str, config, mode: str = "import"):
    """The StePPO controller for `system` (see MODES), checked against `config.env`."""
    import dataclasses

    from steppo.cli import load_paper_model

    if mode == "import":
        artifact = load_paper_model(system)
        model_config, controller = artifact.config, artifact.controller
    else:
        from steppo.configs.base_config import TrainConfig, load_config_from_yaml
        from steppo.envs.ode import ODEEnv
        from steppo.envs.ode.learned_controller import LearnedController
        from steppo.utils.checkpoint import resolve_checkpoint

        run_dir = os.path.join(LOCAL_STEPPO_DIR, system)
        if not os.path.isfile(os.path.join(run_dir, "config.yaml")):
            raise FileNotFoundError(
                f"No trained StePPO model in {run_dir}; run: bash paper/train.sh {system}"
            )
        model_config = load_config_from_yaml(TrainConfig, os.path.join(run_dir, "config.yaml"))
        env = ODEEnv(model_config.env, model_config.rollout_steps)
        controller = LearnedController.from_checkpoint(
            resolve_checkpoint(run_dir), model_config, env
        )
    model_env = dataclasses.asdict(model_config.env)
    env = dataclasses.asdict(config.env)
    differs = sorted(k for k in env if k != "test_bins" and env[k] != model_env.get(k))
    if differs:
        raise ValueError(
            f"{SYSTEMS[system]['config']} differs from the {mode}ed model in env.{differs}"
        )
    return controller


def read_torch_state_dict(path: str) -> dict:
    """`model_state_dict` of a PyTorch checkpoint as NumPy arrays, read without importing torch."""
    archive = zipfile.ZipFile(path)
    root = archive.namelist()[0].split("/")[0]
    dtypes = {
        "FloatStorage": np.float32,
        "DoubleStorage": np.float64,
        "LongStorage": np.int64,
        "IntStorage": np.int32,
        "BoolStorage": np.bool_,
    }

    def rebuild_tensor(storage, offset, size, stride, *_):
        return np.lib.stride_tricks.as_strided(
            storage[offset:], shape=size, strides=[s * storage.itemsize for s in stride]
        ).copy()

    class Unpickler(pickle.Unpickler):
        def find_class(self, module, name):
            if name == "_rebuild_tensor_v2":
                return rebuild_tensor
            if name == "_rebuild_parameter":
                return lambda data, *_: data
            if module == "torch" and name.endswith("Storage"):
                return name
            if module == "collections" and name == "OrderedDict":
                return collections.OrderedDict
            if module.startswith("torch"):
                return lambda *_, **__: None
            return super().find_class(module, name)

        def persistent_load(self, pid):
            _, storage_type, key, _, _ = pid
            return np.frombuffer(archive.read(f"{root}/data/{key}"), dtype=dtypes[storage_type])

    with archive.open(f"{root}/data.pkl") as f:
        return Unpickler(f).load()["model_state_dict"]


class DeepONet:
    """NumPy forward pass of a DeepXDE `DeepONetCartesianProd` (ReLU; one branch/trunk pair per output).

    Matches DeepXDE's independent multi-output strategy: output k is
    branch_k(ξ) · relu(trunk_k(t)) + b_k, with no activation on the last layer
    of either network.
    """

    def __init__(self, state_dict: dict):
        self.params = state_dict
        self.num_outputs = sum(k.startswith("b.") for k in state_dict)

    def _trunk_prefix(self, k: int) -> str:
        return f"trunk.{k}." if self.num_outputs > 1 else "trunk."

    def is_msffn_trunk(self) -> bool:
        return f"{self._trunk_prefix(0)}b0" in self.params

    def layer_sizes(self, net: str) -> list[int]:
        """Layer widths of the "branch" or plain-FNN "trunk" network, input first
        (as DeepXDE's layer_sizes_*). For an MsFFN trunk, use msffn_spec() instead."""
        prefix = f"{net}.0.linears." if self.num_outputs > 1 else f"{net}.linears."
        n_layers = sum(k.startswith(prefix) and k.endswith(".weight") for k in self.params)
        shapes = [self.params[f"{prefix}{j}.weight"].shape for j in range(n_layers)]
        return [shapes[0][1]] + [s[0] for s in shapes]

    def msffn_spec(self) -> tuple[int, list[int]]:
        """(n_sigmas, trunk_layers) read back from an MsFFN trunk's own checkpoint
        shapes, matching the trunk_layers originally passed to _build_msffn_trunk:
        [in_dim, fourier_dim, *hidden_sizes, out_dim]."""
        prefix = self._trunk_prefix(0)
        n_sigmas = 0
        while f"{prefix}b{n_sigmas}" in self.params:
            n_sigmas += 1
        in_dim, half_fourier_dim = self.params[f"{prefix}b0"].shape
        n_hidden = sum(
            k.startswith(f"{prefix}hidden.") and k.endswith(".weight") for k in self.params
        )
        hidden_sizes = [self.params[f"{prefix}hidden.{j}.weight"].shape[0] for j in range(n_hidden)]
        out_dim = self.params[f"{prefix}out.weight"].shape[0]
        return n_sigmas, [in_dim, 2 * half_fourier_dim, *hidden_sizes, out_dim]

    def _fnn(self, prefix: str, x: np.ndarray) -> np.ndarray:
        n_layers = sum(k.startswith(prefix) and k.endswith(".weight") for k in self.params)
        for j in range(n_layers):
            x = x @ self.params[f"{prefix}{j}.weight"].T + self.params[f"{prefix}{j}.bias"]
            if j < n_layers - 1:
                x = np.maximum(x, 0.0)
        return x

    def _msffn(self, prefix: str, x: np.ndarray) -> np.ndarray:
        """NumPy port of _MsFFN.forward: per scale, fixed Gaussian Fourier features
        through shared hidden layers (ReLU every layer), concatenated across scales
        and mapped to out_dim by one final linear layer (no activation)."""
        n_sigmas, _ = self.msffn_spec()
        n_hidden = sum(
            k.startswith(f"{prefix}hidden.") and k.endswith(".weight") for k in self.params
        )
        feats = []
        for i in range(n_sigmas):
            proj = x @ self.params[f"{prefix}b{i}"]
            y = np.concatenate([np.cos(proj), np.sin(proj)], axis=-1)
            for j in range(n_hidden):
                y = (
                    y @ self.params[f"{prefix}hidden.{j}.weight"].T
                    + self.params[f"{prefix}hidden.{j}.bias"]
                )
                y = np.maximum(y, 0.0)
            feats.append(y)
        combined = np.concatenate(feats, axis=-1)
        return combined @ self.params[f"{prefix}out.weight"].T + self.params[f"{prefix}out.bias"]

    def _trunk(self, k: int, t: np.ndarray) -> np.ndarray:
        prefix = self._trunk_prefix(k)
        if self.is_msffn_trunk():
            return self._msffn(prefix, t)
        return self._fnn(f"{prefix}linears.", t)

    def __call__(self, xi, t) -> np.ndarray:
        """Predicted states, shape (len(xi), len(t), num_outputs)."""
        xi = np.asarray(xi, dtype=np.float32).reshape(-1, 1)
        t = np.asarray(t, dtype=np.float32).reshape(-1, 1)
        outputs = []
        for k in range(self.num_outputs):
            tag = f".{k}" if self.num_outputs > 1 else ""
            branch = self._fnn(f"branch{tag}.linears.", xi)
            trunk = np.maximum(self._trunk(k, t), 0.0)
            outputs.append(branch @ trunk.T + self.params[f"b.{k}"])
        return np.stack(outputs, axis=-1)


def deeponet_checkpoint(system: str, domain: str = "complete", mode: str = "import") -> str:
    """Path of the DeepONet checkpoint for `system` trained on `domain` ("complete" or "binned")."""
    if mode == "import":
        from huggingface_hub import snapshot_download

        local = snapshot_download(DEEPONET_REPO, revision=SYSTEMS[system]["deeponet"][domain])
        (checkpoint,) = glob.glob(os.path.join(local, "*.pt"))
        return checkpoint
    found = sorted(
        glob.glob(
            os.path.join(
                LOCAL_DEEPONET_DIR,
                system,
                "models",
                f"deeponet_{system}_retrain_{domain}_final-*.pt",
            )
        )
    )
    if not found:
        raise FileNotFoundError(
            f"No trained DeepONet for {system}/{domain} in {LOCAL_DEEPONET_DIR}; in the DeepONet container run: "
            f"PYTHONPATH=. python research/baselines/deeponet/train_deeponet_unified.py "
            f"--profile retrain --system {system} --domain {domain}"
        )
    return found[-1]


def load_deeponet(system: str, domain: str = "complete", mode: str = "import") -> DeepONet:
    """The DeepONet for `system` trained on `domain` (see deeponet_checkpoint), as NumPy."""
    return DeepONet(read_torch_state_dict(deeponet_checkpoint(system, domain, mode)))


def deeponet_grid(t_end: float) -> np.ndarray:
    """The time grid the DeepONets were trained on."""
    return np.linspace(0.0, t_end, DEEPONET_N_T)


def load_test_set(system: str, config, mode: str = "import") -> dict:
    """Test-split series for PID, StePPO and Oracle: {name: {"mu", "steps", "completed"[, "err_integrated"]}}.

    The tasks, reference and Oracle (steps and trajectory error) come from the
    evaluation dataset. PID and StePPO (see load_steppo) are solved here on the
    same episodes with steppo.cli.BUDGET_MULTIPLIER × rollout_steps steps, so
    that PID reaches t_end on stiff tasks; the policy does not observe the budget. "steps" counts
    accepted plus rejected steps, except for the Oracle (accepted only).
    """
    from steppo.cli import BUDGET_MULTIPLIER
    from steppo.training.error_dist import load_cached_pid_batch
    from steppo.training.pid_solve import env_pid_controller
    from steppo.training.steps_vs_mu import collect_policy_errors
    from steppo.training.trajectory_compare import time_average, to_log10_clipped

    env = config.env
    cached = load_cached_pid_batch(
        env, max_steps=config.rollout_steps, bins=list(env.test_bins), split="test"
    )
    budget = config.rollout_steps * BUDGET_MULTIPLIER
    series = {
        "Oracle": {
            "mu": cached["task_params"],
            "steps": cached["oracle_steps"],
            "completed": cached["oracle_completed"] & cached["ref_completed"],
            "err_integrated": time_average(
                cached["oracle_ts"], to_log10_clipped(cached["oracle_local_err"])
            ),
        }
    }
    for name, controller in (
        ("PID", env_pid_controller(env)),
        ("StePPO", load_steppo(system, config, mode)),
    ):
        series[name] = collect_policy_errors(
            env,
            controller,
            cached["task_params"],
            cached["episode_keys"],
            budget,
            cached["ref_final_y"],
            cached["ref_ts"],
            cached["ref_ys"],
            env.atol,
            ref_completed=cached["ref_completed"],
        )
    over = np.mean(series["StePPO"]["steps"] > config.rollout_steps)
    if over > 0:
        print(
            f"[!] {system}: {over:.1%} of StePPO solves exceed the training budget of {config.rollout_steps} steps"
        )
    return {"cache": cached, **series}


def deeponet_series(model, cached: dict, t_end: float, atol: float) -> dict:
    """DeepONet e_int on the cached test tasks, in the steps_vs_mu series format."""
    from steppo.training.trajectory_compare import log10_time_integrated_error

    t = deeponet_grid(t_end)
    ts = np.broadcast_to(t, (len(cached["task_params"]), len(t)))
    ys = model(cached["task_params"], t)
    return {
        "mu": cached["task_params"],
        "completed": cached["ref_completed"],
        "err_integrated": log10_time_integrated_error(
            cached["ref_ts"], cached["ref_ys"], ts, ys, atol
        ),
    }


def binned_mean(series: dict, value_key: str, edges: np.ndarray) -> np.ndarray:
    """Per-bin mean of `series[value_key]` over completed episodes (NaN for empty bins)."""
    from steppo.utils.figures.ode import bin_stats

    return bin_stats(series, edges, value_key)[0]
